Event/Controllers/PlanEventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Event.DAL;
using Event.Models;
using System.Data;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Data.Entity;
using System.Web.Routing;

namespace Event.Controllers
{
    public class PlanEventController: Controller
    {
        private PlannerContext db = new PlannerContext();

        public ViewResult Index()
        {
            return View(db.PlanEvents.ToList());
        }
    
        // GET
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title, StartDateTime, Location, Description, MaxCountGuest")]PlanEvent planEvent)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.PlanEvents.Add(planEvent);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(planEvent);
        }

        
        public ActionResult Activation()
        {
            int activeEventID = 0;
            ViewBag.Message = "Invalid Activation code.";
            if (RouteData.Values["id"] != null)
            {
                Guid activationCode = new Guid(RouteData.Values["id"].ToString());
                
                
                Guest guest = db.Guests.Where(p => p.ActivationCode == activationCode).FirstOrDefault();
                if (guest != null)
                {
                    foreach(var g in guest.PlanEvents)
                    {
                        activeEventID = g.ID;
                    }
                    db.Guests.Remove(guest);
                    db.SaveChanges();
                    
                }
            }
            TempData["arg"] = activeEventID;
            return RedirectToAction("Details", "Guest");
            
        }

        // GET
        public ActionResult Letter()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Letter(EmailForm model, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<PlanEvent> ev = new List<PlanEvent>();
            ev.Add(db.PlanEvents.Find(id));
            if (ev == null)
            {
                return HttpNotFound();
            }

            Guid activationCode = Guid.NewGuid();
            db.Guests.Add(new Guest
            {
                Email = model.ToEmail,
                ActivationCode = activationCode,
                PlanEvents = ev

                
            });

            db.SaveChanges();    
            if (ModelState.IsValid)
            {
                var body = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
                body += "<br /><br />Please click the following link to activate your account";
                body += "<br /><a href = '" + string.Format("{0}://{1}/PlanEvent/Activation/{2}", Request.Url.Scheme, Request.Url.Authority, activationCode) + "'>Click here to activate your account.</a>";
                var message = new MailMessage();
                message.To.Add(new MailAddress("your@gmail.com")); //replace with valid value
                message.Subject = "Your email subject";
                message.Body = string.Format(body, model.FromName, model.FromEmail, model.Message);
                message.IsBodyHtml = true;
                using (var smtp = new SmtpClient())
                {
                    await smtp.SendMailAsync(message);
                    return RedirectToAction("Sent");
                }
            }
            return View(model);
        }

        public ActionResult Sent()
        {
            return View();
        }
    }

}

Event/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Event Planner", "Index", "PlanEvent", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li>@Html.ActionLink("Create Event", "Create", "PlanEvent")</li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>